gomod:
  proxy: false
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
before:
  hooks:
    - go generate ./...
    - go run github.com/google/go-licenses@latest save ./... --save_path=./notices --force --ignore github.com/pjbgf/sha1cd/cgo --ignore github.com/cloudflare/circl --ignore golang.org/x
builds:
  - id: wiki
    env:
      - CGO_ENABLED=0
    gcflags:
      - ./dontoptimizeme=-N
    ldflags:
      - -s -w -X main.version={{.Version}}
    flags:
      - -trimpath
    mod_timestamp: '{{ .CommitTimestamp }}'
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: gorelease.Dockerfile
    image_templates:
      - "ghcr.io/mdbot/wiki:dev"
    build_flag_templates:
      - --label=org.opencontainers.image.source=https://github.com/mdbot/wiki
    extra_files:
    - notices
