name: Assign closed issues
on:
  push:
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Assign closed issues
        uses: greboid/issue-milestone-manager@v2.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}